const express = require("express");
const router = express.Router();
const { verifyAccessToken } = require("../middlewares/verifyToken");
const { isAdmin } = require("../middlewares/checkRole");
const Ctrls = require("../controllers/order");
router.post("/", verifyAccessToken, Ctrls.createOrder);
router.get("/", verifyAccessToken, Ctrls.getUserOrder);
router.get("/admin", [verifyAccessToken, isAdmin], Ctrls.getOrderByAdmin);
router.put("/status/:oid", [verifyAccessToken, isAdmin], Ctrls.updateStatus);
module.exports = router;
