const router = require("express").Router();
const Ctrls = require("../controllers/user");
const { isAdmin } = require("../middlewares/checkRole");
const { verifyAccessToken } = require("../middlewares/verifyToken");
router.post("/register", Ctrls.register);
router.post("/login", Ctrls.login);
router.get("/current", verifyAccessToken, Ctrls.getCurrentUser);
router.put("/current", verifyAccessToken, Ctrls.updateUser);
router.post("/refresh-token", Ctrls.refreshAccessToken);
router.get("/logout", Ctrls.logout);
router.get("/forgot-password", Ctrls.forgotPassword);
router.put("/reset-password", Ctrls.resetPassword);
// router.use(verifyAccessToken);
// router.get("/users", isAdmin, Ctrls.getUsers);
router.get("/", [verifyAccessToken, isAdmin], Ctrls.getUsers);
router.delete("/", [verifyAccessToken, isAdmin], Ctrls.deleteUser);
router.put("/address/:uid", verifyAccessToken, Ctrls.updateUserAddress);
router.put("/cart", verifyAccessToken, Ctrls.updateCart);
router.put("/:uid", [verifyAccessToken, isAdmin], Ctrls.updateUserByAdmin);
module.exports = router;
